services:
  rap-diggers-explorer-postgres:
    image: postgres:15
    container_name: rap-diggers-explorer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rap-diggers-explorer
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
