export enum ErrorCode {
  // User(s)
  USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
  USER_FORBIDDEN = "USER_FORBIDDEN",
  USER_FORBIDDEN_MAX_PLAYLISTS = "USER_FORBIDDEN_MAX_PLAYLISTS",
  USER_FORBIDDEN_MAX_TRACKS = "USER_FORBIDDEN_MAX_TRACKS",
  USER_FORBIDDEN_MAX_REQUESTS = "USER_FORBIDDEN_MAX_REQUESTS",
  USER_FORBIDDEN_MAX_IMPORTS = "USER_FORBIDDEN_MAX_IMPORTS",

  // Input(s)
  INPUT_INVALID = "INPUT_INVALID",

  // ArtistStatu(s)
  ARTIST_STATUS_NOT_FOUND = "ARTIST_STATUS_NOT_FOUND",

  // Misc(s)
  SPOTIFY_UNKNOWN = "SPOTIFY_UNKNOWN",
}
