export enum ErrorCode {
  // User(s)
  USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
  USER_FORBIDDEN = "USER_FORBIDDEN",
  USER_FORBIDDEN_MAX_PLAYLISTS = "USER_FORBIDDEN_MAX_PLAYLISTS",
  USER_FORBIDDEN_MAX_TRACKS = "USER_FORBIDDEN_MAX_TRACKS",

  // Input(s)
  INPUT_INVALID = "INPUT_INVALID",

  // Misc(s)
  SPOTIFY_UNKNOWN = "SPOTIFY_UNKNOWN",
}
