import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "./_components/ui/toaster";
import { AuthProvider } from "./_contexts/AuthContext";
import { DataProvider } from "./_contexts/DataContext";
import { auth } from "./_libs/auth";
import { cn } from "./_libs/shadcn";
import "./globals.css";

const benzin = localFont({
  src: [
    {
      path: "./_assets/fonts/benzin-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./_assets/fonts/benzin-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-benzin",
  preload: true,
});
const helvetica = localFont({
  src: [
    {
      path: "./_assets/fonts/helvetica-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./_assets/fonts/helvetica-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout = async (props: RootLayoutProps) => {
  const { children } = props;

  const session = await auth();

  return (
    <html lang="en">
      {/* https://github.com/Remix-Design/RemixIcon#cdn */}
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@3.6.0/fonts/remixicon.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={cn(
          "flex min-h-screen bg-background font-helvetica antialiased", //
          benzin.variable,
          helvetica.variable,
        )}
      >
        <DataProvider>
          <AuthProvider session={session}>
            {children}
            <Toaster />
          </AuthProvider>
        </DataProvider>
      </body>
    </html>
  );
};

export default RootLayout;
