import type { Metadata } from "next";
import localFont from "next/font/local";
import "remixicon/fonts/remixicon.css";
import { AuthProvider } from "./_contexts/AuthContext/AuthContext";
import { auth } from "./_libs/auth";
import { cn } from "./_libs/shadcn";
import "./globals.css";

const benzin = localFont({
  src: [
    {
      path: "./_assets/fonts/Benzin-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./_assets/fonts/Benzin-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-benzin",
});
const helvetica = localFont({
  src: [
    {
      path: "./_assets/fonts/Helvetica-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./_assets/fonts/Helvetica-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

const Layout = async (props: LayoutProps) => {
  const { children } = props;

  const session = await auth();

  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen bg-background font-helvetica antialiased", //
          benzin.variable,
          helvetica.variable,
        )}
      >
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
};

export default Layout;
