import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { AuthProvider } from "./_contexts/AuthContext/AuthContext";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";

// @TODO - This ...
const inter = Inter({ subsets: ["latin"] });

// @TODO - This should be updated!
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
