-- AlterTable
ALTER TABLE "ArtistStatus" ADD COLUMN     "skippedAt" TIMESTAMP(3),
ALTER COLUMN "score" DROP NOT NULL,
ALTER COLUMN "score" DROP DEFAULT,
ALTER COLUMN "score" SET DATA TYPE DOUBLE PRECISION;
